site_name: Simples Nacional

repo_url: https://github.com/Interacao-Humano-Computador/2022.2-Grupo3-IHC

theme:
  name: material
  language: pt-BR
  font:
    text: Roboto
  
  palette: 
    - scheme: default
      primary: yellow
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/favicon.png
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.indexes

nav:
  - Planejamento: 
    - Projeto: index.md
    - Sites Analisados: Planejamento/SitesAnalisados.md
    - Metodologias e Processos: Planejamento/Metodologia.md
    - Modelo de Design: Planejamento/ModeloDesign.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Heatmap: Planejamento/Heatmap.md
    - Roadmap: Planejamento/Roadmap.md
    - Políticas:
      - Código de Conduta Para Colaboradores: Politicas/CodigoDeConduta.md
      - Política de Contribuição: Politicas/PolitcaDeContribuicao.md
      - Política de Issue: Politicas/PolitcaDeIssue.md
      - Política de Branch: Politicas/PolitcaDeBranch.md
      - Política de Commit: Politicas/PolitcaDeCommit.md
      - Política de Pull Request: Politicas/PolitcaDePR.md
      - Política de Segurança: Politicas/PolitcaDeSeguranca.md
  - Apresentações/Reuniões:
    - Reunioes: Reunioes/index.md
    - Apresentações:
      - 1º Ponto de Controle: Reunioes/Apresentacoes/Entrega1.md
      - 2º Ponto de Controle: Reunioes/Apresentacoes/Entrega2.md
      - 3º Ponto de Controle: Reunioes/Apresentacoes/Entrega3.md
      - 4º Ponto de Controle: Reunioes/Apresentacoes/Entrega4.md
      - 5º Ponto de Controle: Reunioes/Apresentacoes/Entrega5.md
    - Reuniões:
      - 1ª Reunião: Reunioes/Atas/Reuniao1.md
      - 2ª Reunião: Reunioes/Atas/Reuniao2.md
      - 3ª Reunião: Reunioes/Atas/Reuniao3.md
      - 4ª Reunião: Reunioes/Atas/Reuniao4.md
      - 5ª Reunião: Reunioes/Atas/Reuniao5.md
      - 6ª Reunião: Reunioes/Atas/Reuniao6.md
  - Análise de Requisitos:
    - Análise de Tarefas: Tarefas/Analise.md
    - Perfil de Usúario:
      - Questionário e Perfis de Usuarios: Tarefas/perfilUsuario.md
      - Personas: Tarefas/personas.md
    - Aspectos Éticos: Tarefas/AspectosEticos.md
    - Cenários: Tarefas/Cenarios.md
    - Metas de Usabilidade: Tarefas/MetasUsabilidade.md
    - Caracteristicas da Plataforma: Tarefas/CaracteristicasPlataforma.md
    - Princípios Gerais: Tarefas/PrincipiosGerais.md
    - Guia de Estilo: Tarefas/GuiaDeEstilo.md
    - Termo de consentimento: Tarefas/ModeloTermoConsentimento.md
  - Design, Avaliação e Desenvolvimento:
    - introdução: DesignAvaliacaoDesen/index.md
    - 1º Nível:
      - Análise de Tarefas:
        - Planejamento da Avaliação: DesignAvaliacaoDesen/Nivel1/AnaliseDeTarefas/PlanejamentoAvAnaliseDeTarefas.md
        - Planejamento do Relato : DesignAvaliacaoDesen/Nivel1/AnaliseDeTarefas/PlanejamentoResAnaliseTarefas.md
        - Avaliação : DesignAvaliacaoDesen/Nivel1/AnaliseDeTarefas/AvaliacaoAnaliseDeTarefas.md  
        - Relato de Resultados: DesignAvaliacaoDesen/Nivel1/AnaliseDeTarefas/RelatoResultadosAnaliseTarefas.md
      - Storyboard:
        - Planejamento da Avaliação: DesignAvaliacaoDesen/Nivel1/Storyboard/PlanejamentoAvStoryboard.md
        - Planejamento do Relato : DesignAvaliacaoDesen/Nivel1/Storyboard/PlanejamentoRelatoResuStoryboard.md
        - Avaliação : DesignAvaliacaoDesen/Nivel1/Storyboard/AvaliacaoStoryboards.md
      - Verificação da 1ª Etapa: DesignAvaliacaoDesen/Nivel1/VerificacaoEtapa1.md
    - 2º Nível:
      - Protótipo de Papel:
        - Planejamento da Avaliação: DesignAvaliacaoDesen/Nivel2/ProtPapel/PlanejamentoProtPapel.md
        - Planejamento do Relato : DesignAvaliacaoDesen/Nivel2/ProtPapel/PlanejamentoRelatoResuProtPapel.md
    - 3º Nível:
      - Protótipo de Alta Fidelidade:
        - Planejamento da Avaliação: DesignAvaliacaoDesen/Nivel3/ProtAltaFidelidade/PlanejamentoProtAlta.md
        - Planejamento do Relato : DesignAvaliacaoDesen/Nivel3/ProtAltaFidelidade/PlanejamentoRelatoResuProtAlta.md
    - Testes Piloto: 
      - Storyboard: DesignAvaliacaoDesen/TestesPiloto/TestePilotoStoryboard.md
      - Analise de Tarefas: DesignAvaliacaoDesen/TestesPiloto/TestepilotoAnaliTarefas.md
      - Protótipo de Papel: DesignAvaliacaoDesen/TestesPiloto/TestePilotoProtPapel.md
    - Termos de consentimento:
      - Avaliação da Analise de Tarefas: DesignAvaliacaoDesen/TermosConsentimento/TermoConsentimentoAnaliseTarefas.md
      - Avaliação do Storyboard: DesignAvaliacaoDesen/TermosConsentimento/TermoConsentimentoStoryboard.md
      - Avaliação do protótipo de Papel: DesignAvaliacaoDesen/TermosConsentimento/TermoConsentimentoProtPapel.md