site_name: Simples Nacional

repo_url: https://github.com/Interacao-Humano-Computador/2022.2-Grupo3-IHC

theme:
  name: material
  language: pt-BR
  font:
    text: Roboto
  
  palette: 
    - scheme: default
      primary: yellow
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/favicon.png
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top

nav:
  - Projeto: 
    - Projeto: index.md
  - Planejamento:
    - Sites Analisados: Planejamento/SitesAnalisados.md
    - Metodologias e Processos: Planejamento/Metodologia.md
    - Modelo de Design: Planejamento/ModeloDesign.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Heatmap: Planejamento/Heatmap.md
    - Roadmap: Planejamento/Roadmap.md
    - Políticas:
      - Código de Conduta Para Colaboradores: Politicas/CodigoDeConduta.md
      - Política de Contribuição: Politicas/PolitcaDeContribuicao.md
      - Política de Issue: Politicas/PolitcaDeIssue.md
      - Política de Branch: Politicas/PolitcaDeBranch.md
      - Política de Commit: Politicas/PolitcaDeCommit.md
      - Política de Pull Request: Politicas/PolitcaDePR.md
      - Política de Segurança: Politicas/PolitcaDeSeguranca.md
  - Apresentações/Reuniões:
    - Apresentações:
      - 1º Ponto de Controle: Apresentacoes/PrimeiraEntrega.md
      - 2º Ponto de Controle: Apresentacoes/SegundaEntrega.md
      - 3º Ponto de Controle: Apresentacoes/TerceiraEntrega.md
    - Reuniões:
      - 1ª Reunião: Atas/Reuniao1.md
      - 2ª Reunião: Atas/Reuniao2.md
      - 3ª Reunião: Atas/Reuniao3.md
  - Analise de Requisitos:
    - Analise de Tarefas: Tarefas/Analise.md
    - Perfil de Usúario:
      - Questionário e Perfis de Usuarios: Tarefas/perfilUsuario.md
      - Personas: Tarefas/personas.md
      - Termo de Consentimento: Tarefas/ModeloTermoConsentimento.md
    - Aspectos Éticos: Tarefas/AspectosEticos.md
    - Cenários: Tarefas/Cenarios.md
    - Metas de Usabilidade: Tarefas/MetasUsabilidade.md
    - Caracteristicas da Plataforma: Tarefas/CaracteristicasPlataforma.md
    - Princípios Gerais: Tarefas/PrincipiosGerais.md
    - Guia de Estilo: Tarefas/GuiaDeEstilo.md